### PR TITLE
Update dependency version

### PR DESCRIPTION
**Pull request by justinvasel**
PR to accompany Issue #91 

- Drop support for python versions less than 3.11
- Upgrade `hop-client` from v0.8.0 to v0.9.0
- Drop several dependencies that don't appear to be used
- Upgrade all packages that can be upgraded
- All tests in the suite are passing on my local machine

Resolves: #91, #78

### CODE REVIEW

**Comment by justinvasel** [comment]
Following the merger of this PR, I recommend tagging a new release, so that `snews_cs` can pull in the latest version and upgrade its own dependencies.

**Comment by justinvasel** [comment]
Apologies for the email traffic... I had to do a bunch of tests to get the github workflow working with the new versions of `hop-client` and `pytest`. I ultimately ended up squashing all those commits and resubmitting the PR to keep the commit history clean. Probably can't say the same for your inbox though... :/

**Comment by KaraMelih** [comment]
I think I was able to follow the flow. I can try to test this branch on my local machine next Monday

**Comment by KaraMelih** [comment]
Hi, I could only get back to these PRs now. 
I checked the existing PRs addressing the SQL fixes and datetime conversions. 
Now, these branches https://github.com/SNEWS2/SNEWS_Publishing_Tools/pull/90 and https://github.com/SNEWS2/SNEWS_Coincidence_System/pull/83 should play nicely with each other. While they should in principle not affect this PR, in order for me to run updated dependencies I need working versions of the scripts.

**Review by KaraMelih — APPROVED** [review]

**Pull request merged**
