### PR TITLE
Float timeseries

### PR DESCRIPTION
**Pull request by KaraMelih**
Aimed at fixing https://github.com/SNEWS2/SNEWS_Publishing_Tools/issues/87
~also fixes https://github.com/SNEWS2/SNEWS_Publishing_Tools/issues/97~ (moved this fix to https://github.com/SNEWS2/SNEWS_Publishing_Tools/pull/99)

Previously, we were expecting iso-formattable time strings for all the entries in the expected `timing_series` . <br>
However, this can easily become too large. As was suggested by others, this PR implements a float conversion. 

It first checks if all the values are strings or floats/integers. <br>
 - If they are strings, it converts them to numpy datetime objects, sort by value, look at the relative time delta's from the first ever value in the list. 
 - If they are floats/integers it also checks if the "neutrino_time" is explicitly given. 

Right now, the logic is missing. I do not know if we should always force initial neutrino time too, or should this be fetched from the Coincidence Tier by time tier people? 

I imagine a list of time series starting with 0 is not fully useful if we do not know what the 0 refers to.

### CODE REVIEW

**Comment by KaraMelih** [comment]
Reverted the firedrill fix ([ee7f062](https://github.com/SNEWS2/SNEWS_Publishing_Tools/pull/98/commits/ee7f06274d4db60a99a29229d39a70e7dc5dcf40)), as I added that in a minor patch

**Comment by habig** [comment]
Have we been able to reproduce #87 ?  If there's an unexpected hard limit on message size, we need to take that to scimma as a bug, since the original specs were "sure, you guys can hove anything around including big skymaps"

**Comment by habig** [comment]
Great, thanks.  If we convert that to bytes (since we're sending in ASCII one number is a lot of characters), what's that look like?  I've got the attention of scimma devs at the moment.

**Comment by justinvasel** [comment]
See https://github.com/SNEWS2/SNEWS_Publishing_Tools/issues/87#issuecomment-2105083319 for a potential solution.

**Comment by habig** [comment]
The scimma people report that the default max message size is 1MB.  They're leery to increase that to head off future scaling problems, and are working on a large file offload service.  But: now knowing this we can plan for it, with efficiencies like this PR helping.  Could imagine daisy-chaining things together like SMS messages that go over 140 characters, too.

**Pull request merged**
